### ISSUE TITLE
Possible to make it run in other apps than Finder?

### ISSUE THREAD

**Issue by JayBrown** [objective-see/WhatsYourSign#1]
Is it possible to to make WhatsYourSign run in other applications than the Finder? I'm thinking about Path Finder, ForkLift, Commander One (any of the "Commander" managers, actually).

**Comment by JayBrown** [comment]
Not sure if other file managers are on the agenda, but I've hacked together a quick script that will eventually do the same with shell programs and qlmanager. https://github.com/JayBrown/wys-WhatsYourSign-shell-script-version

**Comment by objective-see** [comment]
Since it uses Finder-specific interfaces (i.e. a "Finder Sync"), it will only work with Apple's Finder.app :\
