### ISSUE TITLE
Add check for notarization

### ISSUE THREAD

**Issue by prbsparx** [objective-see/WhatsYourSign#10]
In 10.14 Apple started requiring new apps to be notarized. Would be great to be able to see notarization status in WhatsYourSign.

**Comment by objective-see** [comment]
Added!  

![image](https://user-images.githubusercontent.com/11327812/82788374-10f87e80-9e04-11ea-9b77-7150cce1cba2.png)

If you want to give the beta whirl, that'd be great: https://bitbucket.org/objective-see/deploy/downloads/WhatsYourSign_1.6.0_BETA.zip

**Comment by objective-see** [comment]
Latest release version now supports notarization checks!
