### ISSUE TITLE
installer screen issue

### ISSUE THREAD

**Issue by macMikey** [objective-see/WhatsYourSign#11]
this is v. 1.6.0
<img width="458" alt="Screen Shot 2020-05-25 at 14 09 44" src="https://user-images.githubusercontent.com/10867016/82835349-c32a5780-9e91-11ea-838d-6f27be833965.png">

**Comment by alvarnell** [comment]
Not seeing this in Mojave.

**Comment by objective-see** [comment]
@macMikey can you try the latest beta (just pushed a new one): [https://bitbucket.org/objective-see/deploy/downloads/WhatsYourSign_1.6.0_BETA.zip](https://bitbucket.org/objective-see/deploy/downloads/WhatsYourSign_1.6.0_BETA.zip)

...if it still has the same issue, what OS/mode settings (dark, light, etc) are you using? 

thanks!

**Comment by objective-see** [comment]
fixed in: https://bitbucket.org/objective-see/deploy/downloads/WhatsYourSign_1.6.1.zip
