### ISSUE TITLE
Reports incorrect hashes for large files but works for small files

### ISSUE THREAD

**Issue by urbanadventurer** [objective-see/WhatsYourSign#12]
# Windows 10 ISO hash does not match (5.27GB)

Correct hash is a9efd2329ed805a6a58e0e0101f9b22ad4031e80e2c663c571cd004db26d2f31 according to Microsoft.com.

shasum and openssl report the file has the expected hash.

```
shasum -a 256 -b ./Win10_2004_English_x64.iso
a9efd2329ed805a6a58e0e0101f9b22ad4031e80e2c663c571cd004db26d2f31 *./Win10_2004_English_x64.iso

openssl dgst -sha256  ./Win10_2004_English_x64.iso
SHA256(./Win10_2004_English_x64.iso)= a9efd2329ed805a6a58e0e0101f9b22ad4031e80e2c663c571cd004db26d2f31
```

What's my Sign does not report the same hash

![image](https://user-images.githubusercontent.com/101783/92300161-fb1a5e00-ef9b-11ea-876c-e45b6c4dae0c.png)

Other algorithms for this file also do not match.
```
md5  ./Win10_2004_English_x64.iso
MD5 (./Win10_2004_English_x64.iso) = 3cf9848ce17271e7c895366bdad98a8e

shasum -a 1  -b ./Win10_2004_English_x64.iso
71a288febd984839b575efb3bd9bc9ab7471b604 *./Win10_2004_English_x64.iso

shasum -a 512 ./Win10_2004_English_x64.iso
188f0dcd34ec0ea1e23ff5f236f77b4fb56a3d46995e0f2e594dd121fb86830b4d3bc55853a23ec0090f67f757f691c4812b864ce503192edc34fd66413ce6a3  ./Win10_2004_English_x64.iso
```

Other tests
- A smaller file at 2.28GB gave the same result with What's Your Sign as command line tools.
- A larger file at 7GB did not match.

My operating system
- Catalina 10.15.6

**Comment by objective-see** [comment]
Thanks for the bug report! 
...fixed in v2.0.0 :)
