### ISSUE TITLE
Extra WhatsYourSign process

### ISSUE THREAD

**Issue by Chasapple4** [objective-see/WhatsYourSign#13]
Over time or some other trigger there will be more than 1 WhatsYourSign process running (as can be seen in Activity Monitor).

Does anyone know what can be done to prevent WhatsYourSign from having more than 1 process?

<img width="309" alt="tra WhatsYourSign processes" src="https://user-images.githubusercontent.com/69293411/96527196-cfe28a00-123c-11eb-9253-df43fe39b5cd.png">

**Comment by Chasapple4** [comment]
Still happens on macOS 11.0.1

<img width="262" alt="image" src="https://user-images.githubusercontent.com/69293411/99132808-e3330c00-25d4-11eb-83f2-8abcc1f4ccb5.png">

**Comment by ajs256** [comment]
This happens to me, too.

**Comment by objective-see** [comment]
WYS is a "Finder Sync" (Apple parlance for an Finder plugin) 
...by design Finder.app will load multiple instance of such plugins 🤷

Will dig into this more, to see if there is anything that can be done to override this system behavior.

**Comment by Chasapple4** [comment]
Seeing it still in version 2.2.3
<img width="592" alt="image" src="https://github.com/user-attachments/assets/2c134bb6-6c1d-42ab-84e3-1d07a819d08a">

**Comment by Chasapple4** [comment]
@objective-see 
Before 3.0.0
<img width="602" alt="image" src="https://github.com/user-attachments/assets/5868d8a5-a31b-4af0-82dd-bdbdb0a0ce8f">

Will see in a bit if they are gone
