### ISSUE TITLE
Detected by VirusTotal

### ISSUE THREAD

**Issue by ajs256** [objective-see/WhatsYourSign#16]
https://www.virustotal.com/gui/file/1ffe4b7342ee5d9d35fa8d7dbfc9bdf399ed8ac3b368e58bb78f3fd0f1d772d2/detection

KnockKnock complained that this app was detected by VirusTotal.

**Comment by objective-see** [comment]
Thanks!
Definitely a false positive that's now been cleared up!

![image](https://user-images.githubusercontent.com/11327812/104644545-f8b6c780-5651-11eb-8cfa-e4934e4dd071.png)
