### ISSUE TITLE
Can't read /usr/sbin/cupsd

### ISSUE THREAD

**Issue by Flashget** [objective-see/WhatsYourSign#19]
![image](https://user-images.githubusercontent.com/4050460/150173553-37bcae08-1e74-4c29-9e82-71b4b26ce6d4.png)

same in TaskExplorer

![image](https://user-images.githubusercontent.com/4050460/150173652-6e4566c9-679d-4bfc-86a4-c79b3760f9a1.png)

Is it normal or a bug or am I infected? Thank you

**Comment by martinsstuff** [comment]
Looks exactly the same (Error 100013) on my fresh macOS install (Intel Mac).

**Comment by objective-see** [comment]
Addressed in v2.1.0, which now specifies if a file cannot be accessed (permissions):

<img width="692" alt="Screenshot 2023-05-26 at 18 43 32" src="https://github.com/objective-see/WhatsYourSign/assets/11327812/b7f4212c-cdc8-491d-a44d-759adc06bdd8">
