### ISSUE TITLE
No longer reporting notarization

### ISSUE THREAD

**Issue by jwwalker** [objective-see/WhatsYourSign#20]
After updating What's Your Sign to the latest version, it no longer tells me that things are notarized, just that they're signed.  I'm running macOS 13.4.1 (22F82).

**Comment by objective-see** [comment]
Good catch! 🙏🏽 

This should be fixed in v2.2.1:
<img width="752" alt="Screenshot 2023-07-07 at 19 47 58" src="https://github.com/objective-see/WhatsYourSign/assets/11327812/f20fe580-649c-49c1-aa75-4383aaa4659b">

**Comment by jwwalker** [comment]
Yes, version 2.2.1 is working now, thanks!
