### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by mrdaveanderson** [objective-see/WhatsYourSign#5]
Hello,

Can you please add dark mode support? :)

Thanks,
-Dave

**Comment by objective-see** [comment]
Mahalo for your patience! 
Just pushed some code that adds dark mode:

![image](https://user-images.githubusercontent.com/11327812/82788565-616fdc00-9e04-11ea-8f80-313fe1baf904.png)

If you want to test the beta (with the fixes/improvements): https://bitbucket.org/objective-see/deploy/downloads/WhatsYourSign_1.6.0_BETA.zip

**Comment by objective-see** [comment]
Latest released version now supports dark mode 🖤
