### ISSUE TITLE
Not Working in macOS Catalina

### ISSUE THREAD

**Issue by michaelfm1211** [objective-see/WhatsYourSign#7]
In macOS Catalina WhatsYourSign no longer works. The option does not appear in Finder. I reinstalled WhatsYourSign and the problem persists.

**Comment by relikd** [comment]
Works for me. Finder shows "Signing Info" and opens WYS accordingly. However, I find it quite dubious that Activity Monitor shows 6 running instances of WYS even though I haven't used it since reboot.

**Comment by michaelfm1211** [comment]
I retried it and it works now. Probably was a bug in macOS fixed in a software update sometime between October and January.
