### ISSUE TITLE
Not working on macOS 10.15.3 (Catalina)

### ISSUE THREAD

**Issue by Repg** [objective-see/WhatsYourSign#8]
On macOS 10.15.3:

1. The installer pops up with a "Failed installation" at first attempt (logged in as administrator and / or standard user)

2. Right / control click on the Calculator.app icon in the /System/Applications folder (as the example in the first screenshot on the welcome page) and / or any other Applications in the same directory the menu option "Signing Info" is missing.

**Comment by steakknife** [comment]
Can confirm also. 😢

**Comment by objective-see** [comment]
Mahalo for your patience! 
Just a pushed a beta with improved Catalina compatibility: 

If you want to test the beta (with the fixes/improvements): https://bitbucket.org/objective-see/deploy/downloads/WhatsYourSign_1.6.0_BETA.zip

**Comment by objective-see** [comment]
Latest released version now works with Catalina
...unfortunately as it uses a Finder-specific interface, it will only work with Finder.app
