### ISSUE TITLE
Not working on macOS 10.15.x (Catalina)

### ISSUE THREAD

**Issue by med-pro-123** [objective-see/WhatsYourSign#9]
Very good tool for macOS security, but on macOS 10.15.x has same problems
Is this project still in development?
Thanks

**Comment by objective-see** [comment]
Mahalo for your patience! 
Just a pushed a beta with improved Catalina compatibility: 

If you want to test the beta (with the fixes/improvements): https://bitbucket.org/objective-see/deploy/downloads/WhatsYourSign_1.6.0_BETA.zip

**Comment by objective-see** [comment]
Latest released version now works with Catalina
